### ISSUE TITLE
Stop clicking in relax when cursor is not on circles

### ISSUE THREAD

**Issue by DioXazin3** [maplesyrupuwu/Maple-for-osu#6]
**Describe your proposal**
Basically what i was thinking about with this.. is when you use relax, it should not click when your cursor is not on circles, i´ve seen this feature on some non-paid cheetos

**Why do you think your solution is better?**
Would be less suspicious if someone (on twitch/stream) asked you to stop clicking, so it will not click when your cursor would be out of circles

**Additional context**
Hope you will give it a try o/

**Comment by maplesyrupuwu** [comment]
It's a part of our relax's system that prevents effortless misses. It won't be changed.

> Would be less suspicious if someone (on twitch/stream) asked you to stop clicking

rxv2 will be toggleable mid gameplay.
