### ISSUE TITLE
scroll bar

### ISSUE THREAD

**Issue by Keycode66** [maplesyrupuwu/Maple-for-osu#8]
**Describe your proposal**

Add a scroll bar for menu since my scroll wheel has been broken for 3 years and i havent been able to scroll on any internal menu for ages

**Why do you think your solution is better?**

if your scroll wheel doesnt work like myself

**Additional context**

**Comment by maplesyrupuwu** [comment]
Scrollbar will look horrible. Implementing something else like an arrow button on overflow is way too much effort imo.
This may sound a bit rude, but can't you afford a new mouse if you can afford a 10eur/mo cheat?
