### ISSUE TITLE
Show misses with RX/AP mods enabled

### ISSUE THREAD

**Issue by axu222** [maplesyrupuwu/Maple-for-osu#9]
**Describe your proposal**

An option to show misses while using RX/AP mods

**Why do you think your solution is better?**

N/A

**Additional context**

Just a nice feature to have, some custom clients have it built-in so you may be able to figure out how to implement it by looking at their source code (I'm not sure if this is how it works as I have no coding experience)

**Comment by maplesyrupuwu** [comment]
It's not how it works and it's too much effort, sorry.
